### ISSUE TITLE
Not Working for Messaging Conversations

### ISSUE THREAD

**Issue by faisyou** [GenesysCloudBlueprints/digital-messaging-translator-blueprint#6]
The Blue print is currently not working for Messaging conversations - when I debug the issue I found the root cause of the problem is on following line (line no 80) of the onMessage Function in the main.js

} else if (data.eventBody.conversationId != currentConversationId) {

This should be as follows

} else if (data.eventBody**.id** != currentConversationId) {

**Comment by crespino4** [comment]
Thanks for reporting this.  We will work to get the blueprint updated with the proper fix.
